import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { useEffect, useState } from "react";
import { NextPage } from "next";
import { api } from "~/utils/api";
import TaskList from "~/components/TaskList";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import { Task } from "@prisma/client";
import Modal from "~/components/Modal";

export default function Home() {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    async function getTasks() {
      const response = await fetch("/api/")
      /* eslint-disable */
      const data = await response.json()
      setTasks(data.message)
    }
    getTasks();
  })
  const user = useUser();
  const { data } = api.post.getAll.useQuery();
  //api.post.create.useQuery({name: "Test", desc: "Test"});
    /* eslint-enable */
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <Navbar/>
        <div className="flex flex-col">
          <TaskList tasks={data as Task[]}/>
        </div>
        <Modal/>
      </main>
    </>
  );
}
