import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { useEffect, useState } from "react";
import { NextPage } from "next";
import { api } from "~/utils/api";
import TaskList from "~/components/TaskList";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import { Task } from "@prisma/client";

export default function Home() {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    async function getTasks() {
      const response = await fetch("/api/")
      // eslint-disable-next-line
      const data = await response.json()
      /* eslint-disable */
      setTasks(data.message)
    }
    getTasks();
  })
  const user = useUser();
  const { data } = api.post.getAll.useQuery();
    /* eslint-enable */
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <Navbar/>
        <div className="flex flex-col">
          <TaskList tasks={data as Task[]}/>
        </div>
        <div className="fixed right-5 bottom-5">
          <button className="btn btn-primary rounded-full btn-lg">
            Add Task
          </button>
        </div>
      </main>
    </>
  );
}
